# Generated by Django 3.1.3 on 2020-12-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201203_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='ssn',
            field=models.IntegerField(),
        ),
    ]
