# Generated by Django 3.1.3 on 2020-12-03 19:01

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201203_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=254),
        ),
    ]
